# Numpy

Install Numpy

In [244]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


Check Numpy Version

In [245]:
import numpy as np
print("NumPy version:{}".format(np.__version__))

NumPy version:1.26.4


## NumPy array

In [246]:
import numpy as np
#Define simple list in Python
list = [0,1,2,3,4]

In [247]:
#Convert list in NumPy array
arr = np.array(list)

In [248]:
# Print content of arr and his type
print ("arr content: {}\n".format(arr))
print ("arr type: {}".format(type(arr)))

arr content: [0 1 2 3 4]

arr type: <class 'numpy.ndarray'>


## Operazioni Matematiche 1

In [249]:
import numpy as np

#Define simple list in Python
list = [0,1,2,3,4]

#Convert list in NumPy array
arr = np.array(list)

In [250]:
#Print content of arr
print ("arr content: {}".format(arr))

arr content: [0 1 2 3 4]


Add

In [251]:
#Add 4 to all the arr items
arr = arr + 4

In [252]:
#Print arr after sum operation
print ("arr content after add operation (+4): {}".format(arr))

arr content after add operation (+4): [4 5 6 7 8]


## Operazioni Matematiche 2

In [253]:
import numpy as np

#Define simple list in Python
list = [0,1,2,3,4]

#Convert list in NumPy array
arr = np.array(list)

Add

In [254]:
#Add 4 to all the arr items
arr = arr + 4

In [255]:
#Print arr after sum operation
print ("arr content after add operation (+4): {}".format(arr))

arr content after add operation (+4): [4 5 6 7 8]


Subtract

In [256]:
#Subtract 2 to all the items in arr
arr = arr - 2

In [257]:
#Print arr after subtraction operation
print ("arr content after subtraction operation (-2): {}".format(arr))

arr content after subtraction operation (-2): [2 3 4 5 6]


Multiply

In [258]:
#Multiply 4 to all the arr items
arr = arr * 4

In [259]:
#Print arr after multiplication operation
print ("arr content after multiplication operation (*4): {}".format(arr))

arr content after multiplication operation (*4): [ 8 12 16 20 24]


Divide

In [260]:
#Divide by 2 all the arr items
arr = arr / 2

In [261]:
#Print arr after division operation
print ("arr content after division operation (/2): {}".format(arr))

arr content after division operation (/2): [ 4.  6.  8. 10. 12.]


# Attributi Type e Shape 

## Type e Shape Parte 1

In [262]:
import numpy as np

#Define simple list in Python
list = [0,1,2,3,4]

#Convert list in NumPy array
arr = np.array(list)

In [263]:
#Print content of arr
print ("arr content: {}".format(arr))

arr content: [0 1 2 3 4]


Print arr shape and type

In [264]:
print ("arr shape : {}".format(arr.shape))

arr shape : (5,)


In [265]:
print ("arr type: {}",format(arr.dtype))

arr type: {} int32


## Type e Shape Parte 2

In [266]:
import numpy as np

#Different type
arr1 = np.array([1.1,2.0,3.2])

In [267]:
#Print arr1 shape and type
print ("arr1 shape : {}".format(arr1.shape))
print ("arr1 type: {}",format(arr1.dtype))

arr1 shape : (3,)
arr1 type: {} float64


In [268]:
#Define simple 2d list in Python
list2 = [[5,6,7],[8,9,10]]

In [269]:
#Convert list 2d in NumPy array
arr_2 = np.array(list2)

In [270]:
#Print arr1 shape and type
print ("arr1 shape : {}".format(arr_2.shape))
print ("arr1 type: {}",format(arr_2.dtype))

arr1 shape : (2, 3)
arr1 type: {} int32


In [271]:
#Print content of arr_2
print ("arr_2 content: {}".format(arr_2))

arr_2 content: [[ 5  6  7]
 [ 8  9 10]]


# Cambiare Tipo

In [272]:
import numpy as np

#Define simple 2d list in Python
list2 = [[0,1,2],[3,4,5],[6,7,8]]

#Convert list2 in NumPy array 2d
arr_2 = np.array(list2)

#Print content of arr_2
print ("arr_2 content: {}".format(arr_2))

arr_2 content: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [273]:
#Print arr_2 shape and type
print ("arr_2 shape : {}".format(arr_2.shape))
print ("arr_2 type: {}",format(arr_2.dtype))

arr_2 shape : (3, 3)
arr_2 type: {} int32


## Cambiare Tipo Parte 1 "Float"

In [274]:
import numpy as np

#Define simple 2d list in Python
list2 = [[0,1,2],[3,4,5],[6,7,8]]

In [275]:
#Convert integer list2 in NumPy array of float items
arr_2f = np.array(list2, dtype='float')

In [276]:
#Print content of arr_2f
print ("arr_2f content: {}".format(arr_2f))

arr_2f content: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [277]:
#Print arr_2f shape and type
print ("arr_2f shape : {}".format(arr_2f.shape))
print ("arr_2f type: {}",format(arr_2f.dtype))

arr_2f shape : (3, 3)
arr_2f type: {} float64


## Cambiare Tipo Parte 2 "Float"

In [278]:
import numpy as np

#Define simple 2d list in Python
list2 = [[0,1,2],[3,4,5],[6,7,8]]

Convert list2 in NumPy array 2d

In [279]:
arr_2 = np.array(list2)

In [280]:
arr_2f = np.array(list2, dtype='float')

Change arr_2f items to integer type through use of astype() function

In [281]:
arr_2i=arr_2f.astype('int')

In [282]:
#Print content of arr_2i
print ("arr_2i content: {}".format(arr_2i))

arr_2i content: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [283]:
#Print arr_2i shape and type
print ("arr_2i shape : {}".format(arr_2i.shape))
print ("arr_2i type: {}",format(arr_2i.dtype))

arr_2i shape : (3, 3)
arr_2i type: {} int32


In [284]:
#Print arr_2f shape and type
print ("arr_2f shape : {}".format(arr_2f.shape))
print ("arr_2f type: {}",format(arr_2f.dtype))

arr_2f shape : (3, 3)
arr_2f type: {} float64


# Array Boolean

In [285]:
import numpy as np

In [286]:
#Create a boolean array
arr_2b = np.array([1,0,1],dtype='bool')

In [287]:
#Print content of arr2_b
print("arr_2b content: {}".format(arr_2b))

arr_2b content: [ True False  True]


In [288]:
#Print arr_2b shape and type
print ("arr_2b shape: {}".format(arr_2b.shape))
print ("arr_2b type: {}".format(arr_2b.dtype))

arr_2b shape: (3,)
arr_2b type: bool


# Array Object

In [289]:
import numpy as np

#Create an object array to hold numbers as well as strings
arr_obj = np.array([1, 'a'], dtype='object')

In [290]:
#Print content of arr_obj
print("arr_obj content: {}".format(arr_obj))

arr_obj content: [1 'a']


In [291]:
#Print arr_obj shape and type
print("arr_obj shape: {}".format(arr_obj.shape))
print("arr_obj type: {}".format(arr_obj.dtype))

arr_obj shape: (2,)
arr_obj type: object


# Array 2D vs 3D

In [292]:
Create 2d NumPy array

SyntaxError: invalid decimal literal (682185542.py, line 1)

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3),(4,5,6)])

In [ ]:
#Print content of arr_2d
print("arr_2d content: {}".format(arr_2d))

In [ ]:
#Print arr_2d shape and type
print ("arr_2d shape: {}".format(arr_2d.shape))
print ("arr_2d type: {}".format(arr_2d.dtype))

Create 3d NumPy array

In [ ]:
import numpy as np

#Create 3d NumPy array
arr_3d = np.array([[[1, 2,3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])

In [ ]:
#Print content of arr_3d
print("arr_3d content: {}".format(arr_3d))

In [ ]:
#Print arr_3d shape and type
print ("arr_3d shape: {}".format(arr_3d.shape))
print ("arr_3d type: {}".format(arr_3d.dtype))

# Zeros Arrays NumPy

Create 2d NumPy array af all zeros

In [ ]:
import numpy as np

#Create 2d NumPy array af all zeros
arr_zeros = np.zeros(shape=(2,2),dtype=np.int8,order='C')

In [ ]:
#Print content of arr_zeros
print ("arr_zeros content: {}".format(arr_zeros))

arr_zeros content: [[0 0]
 [0 0]]


In [ ]:
#Print arr_zeros shape and type
print ("arr_zeros shape: {}".format(arr_zeros.shape))
print ("arr_zeros type: {}".format(arr_zeros.dtype))

arr_zeros shape: (2, 2)
arr_zeros type: int8


# Ones Arrays NumPy

In [ ]:
import numpy as np

#Create 2d NumPy array af all ones
arr_ones = np.ones(shape=(2,2),dtype=np.int8,order='C')

In [ ]:
#Print content of arr_ones
print ("arr_ones content: {}".format(arr_ones))

arr_ones content: [[1 1]
 [1 1]]


In [ ]:
#Print arr_ones shape and type
print ("arr_ones shape: {}".format(arr_ones.shape))
print ("arr_ones type: {}".format(arr_ones.dtype))

arr_ones shape: (2, 2)
arr_ones type: int8


# Reshape Array

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3), (4,5,6)])

#Print content of arr_2d
print ("arr_2d content: {}".format(arr_2d))

#Print arr_2d shape and type
print ("arr_2d shape: {}".format(arr_2d.shape))
print ("arr_2d type: {}".format(arr_2d.dtype))

arr_2d content: [[1 2 3]
 [4 5 6]]
arr_2d shape: (2, 3)
arr_2d type: int32


Reshape a numpy Array

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3), (4,5,6)])

arr_2dr = arr_2d.reshape(3,2)

In [ ]:
#Print content of arr_2dr
print ("arr_2dr content: {}".format(arr_2dr))

#Print arr_2dr shape and type
print ("arr_2dr shape: {}".format(arr_2dr.shape))
print ("arr_2dr type: {}".format(arr_2dr.dtype))

arr_2dr content: [[1 2]
 [3 4]
 [5 6]]
arr_2dr shape: (3, 2)
arr_2dr type: int32


# Flatten Array

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3), (4,5,6)])

#Print content of arr_2d
print ("arr_2d content: {}".format(arr_2d))

#Print arr_2d shape and type
print ("arr_2d shape: {}".format(arr_2d.shape))
print ("arr_2d type: {}".format(arr_2d.dtype))

arr_2d content: [[1 2 3]
 [4 5 6]]
arr_2d shape: (2, 3)
arr_2d type: int32


Flatten a numpy Array

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3), (4,5,6)])

arr_1d = arr_2d.flatten()

In [ ]:
#Print content of arr_1d
print ("arr_1d content: {}".format(arr_1d))

#Print arr_1d shape and type
print ("arr_1d shape: {}".format(arr_1d.shape))
print ("arr_1d type: {}".format(arr_1d.dtype))

arr_1d content: [1 2 3 4 5 6]
arr_1d shape: (6,)
arr_1d type: int32


# Hstack vs Vstack

In [ ]:
import numpy as np

#Create two 2d NumPy array
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

In [ ]:
#Print content of arr_1
print ("arr_1 content: {}".format(arr_1))

arr_1 content: [1 2 3]


In [ ]:
#Print content of arr_2
print ("arr_2 content: {}".format(arr_2))

arr_2 content: [4 5 6]


In [ ]:
#Print arr_1 shape and type
print ("arr_1 shape: {}".format(arr_1.shape))
print ("arr_1 type: {}".format(arr_1.dtype))

arr_1 shape: (3,)
arr_1 type: int32


In [ ]:
#Print arr_2 shape and type
print ("arr_2 shape: {}".format(arr_2.shape))
print ("arr_2 type: {}".format(arr_2.dtype))

arr_2 shape: (3,)
arr_2 type: int32


Hstack: Horizontal Append

In [ ]:
happ = np.hstack((arr_1,arr_2))
print ("Horizontal Append: {}".format(happ))

Horizontal Append: [1 2 3 4 5 6]


Vstack: Vertical Append

In [ ]:
vapp = np.vstack((arr_1,arr_2))
print ("Vertical Append: {}".format(vapp))

Vertical Append: [[1 2 3]
 [4 5 6]]


# How to create and edit Numpy Array

## Asarray

In [ ]:
import numpy as np

#Create matrix of all ones
A = np.matrix(np.ones((4,4)))

#Print content of A
print ("A content: {}".format(A))

A content: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


The change is made on the third line because the indexing starts at 0

Convert the input to an array to make change 

In [ ]:
#The change is made on the third line because the indexing starts at 0
np.asarray(A)[2] = 2

In [ ]:
#Print content A after the change
print("A content after the change: {}".format(A))

A content after the change: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


## Arange

In [ ]:
import numpy as np

#Create array with numpy.arange() of 10 elements
arr = np.arange(1, 11)

#Print content of arr
print ("arr content: {}".format(arr))

arr content: [ 1  2  3  4  5  6  7  8  9 10]


Create array with numpy.arange() of 4 elements and step = 4

In [ ]:
#Create array with numpy.arange() of 4 elements and step = 4
arr_1 = np.arange(1, 14,4)

In [ ]:
#Print content of arr_1
print ("arr_1 content (step = 4): {}".format(arr_1))

arr_1 content (step = 4): [ 1  5  9 13]


## Linspace

In [ ]:
import numpy as np

#Create array with numpy.linspace() of 10 elements
arr = np.linspace(1.0, 5.0, num=10)

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [ ]:
#Print content of arr
print ("arr content: {}".format(arr))

arr content: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
#Create array with numpy.linspace() of 5 with endpoint=False
arr_1 = np.linspace(1.0, 5.0, num=5, endpoint=False)

In [ ]:
# Print content of arr_1
print ("arr_1 content: {}".format(arr_1))

arr_1 content: [1.  1.8 2.6 3.4 4.2]


## Logspace

Return numbers spaced evenly on a log scale.

In [ ]:
import numpy as np

#Create array with numpy.logspace() of 4 elements
arr = np.logspace(3.0, 4.0, num=4)

In [ ]:
#Print content of arr
print ("arr content: {}".format(arr))

arr content: [ 1000.          2154.43469003  4641.58883361 10000.        ]


# Indicizzazione

In [ ]:
import numpy as np

#Create 2d NumPy array
arr_2d = np.array([(1,2,3), (4,5,6)])

Print content

In [ ]:
#Print content of arr_2d
print ("arr_2d content: {}".format(arr_2d))

Print first row

In [ ]:
#Print first row of arr_2d
print ("first row of arr_2d: {}".format(arr_2d[0]))

Print second row

In [ ]:
#Print second row of arr_2d
print ("second row of arr_2d: {}".format(arr_2d[1]))

Print first column

In [ ]:
#Print first column of arr_2d
print ("first column of arr_2d: {}".format(arr_2d[:,0]))

Print second column

In [ ]:
#Print second column of arr_2d
print ("second column of arr_2d: {}".format(arr_2d[:,1]))

Print third column

In [ ]:
#Print third column of arr_2d
print ("third column of arr_2d: {}".format(arr_2d[:,2]))

Print first two elements of the second row

In [ ]:
#Print first two elements of the second row of arr_2d
print ("first two elements of arr_2d: {}".format(arr_2d[1,:2]))

# Funzioni Statistiche

## Normal distribution

In [ ]:
import numpy as np

#Generate random number from normal distribution
normal_array = np.random.normal(5, 0.5, 10)

In [ ]:
#Print content of normal_array
print ("normal_array content: {}".format(normal_array))

Min

In [ ]:
#Min
print("normal_array min: {}".format(np.min(normal_array)))

Max

In [ ]:
#Max
print("normal_array max: {}".format(np.max(normal_array)))

Mean

In [ ]:
#Mean
print("normal_array mean: {}".format(np.mean(normal_array)))

Median

In [ ]:
#Median
print("normal_array median: {}".format(np.median(normal_array)))

Standard deviation

In [ ]:
#Standard deviation
print("normal_array standard deviation: {}".format(np.std(normal_array)))